language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: kwasniewski.mateusz@gmail.com
  api_key:
    secure: Hrq6Te/CCiHIbnS3OoMdY5yCz22BBT/Rxyg+y3uKSIl4gNZen89SieBjZHV6P3zqitUI9Bof5pWCtIa+2W7WuR3H+Rac214M4CehvgAoo1VD1oms5lZ1Vqq/xotuf4QFg41d8Yo/Hn2aS+JHbpcdzgwEpeEKYqSswVIbnkdkGF0=
  on:
    tags: true
    repo: Schibsted-Tech-Polska/nodesi

after_success:
- npm run coverage
- node_modules/.bin/nyc report --reporter=text-lcov | node_modules/.bin/coveralls
